spring.application.name=docEditor

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/doc_editor
spring.datasource.username=root
spring.datasource.password=adi@0913

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080